### ISSUE TITLE
App keep crashing at startup

### ISSUE THREAD

**Issue by scropion86** [open-wa/wa-automate-deploy-heroku#125]
i think the reason is that app should wait before click or navigate as per the explanations in [this ](https://lifesaver.codes/answer/execution-context-was-destroyed-most-likely-because-of-a-navigation-3323)
also in the [docs](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageclickselector-options)

here is the log

thanks' 

```
2022-03-03T05:06:25.192175+00:00 heroku[web.1]: Starting process with command `/bin/sh -c PORT\=\11051\ WA_PORT\=\11051\ node\ ./node_modules/@open-wa/wa-automate/bin/server.js\ --use-chrome\ --force-port\=\11051\ --in-docker\ --qr-timeout\ 0`
2022-03-03T05:06:27.304804+00:00 app[web.1]: - session_STARTUP
2022-03-03T05:06:27.309571+00:00 app[web.1]: - DEBUG - PORT: 11051
2022-03-03T05:06:27.310094+00:00 app[web.1]: - DEBUG - flags: {"sessionId":"session","ev":false,"executablePath":"/usr/bin/google-chrome-stable","botPressUrl":"","debug":true,"keepUpdated":true,"port":11051,"popup":true,"keepAlive":false,"disableSpins":true,"socket":"","sessionData":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","useChrome":true,"forcePort":11051,"inDocker":true,"qrTimeout":0,"noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"emitUnread":false}
2022-03-03T05:06:27.310692+00:00 app[web.1]: - DEBUG - env vars: {"WA_EV":"false","WA_EXECUTABLE_PATH":"/usr/bin/google-chrome-stable","WA_BOT_PRESS_URL":"","WA_DEBUG":"true","WA_KEEP_UPDATED":"true","WA_PORT":"11051","WA_POPUP":"true","WA_KEEP_ALIVE":"false","WA_DISABLE_SPINS":"true","WA_WEBHOOK":"false","WA_SOCKET":"","WA_SESSION_DATA":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","WA_USE_CHROME":"true"}
2022-03-03T05:06:27.311073+00:00 app[web.1]: - Launching EASY API
2022-03-03T05:06:27.329570+00:00 app[web.1]: - Selected port is free
2022-03-03T05:06:27.330242+00:00 app[web.1]: - --ev/-e expecting URL - invalid URL.
2022-03-03T05:06:27.330838+00:00 app[web.1]: - Generating Swagger Spec
2022-03-03T05:06:28.076371+00:00 app[web.1]: - Postman collection generated: open-wa-session.postman_collection.json
2022-03-03T05:06:28.182428+00:00 app[web.1]: - API collections (swagger + postman) generated successfully
2022-03-03T05:06:28.664585+00:00 app[web.1]: ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.31.7                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
2022-03-03T05:06:28.766641+00:00 app[web.1]: You can also authenticate the session at: NA
2022-03-03T05:06:28.767556+00:00 app[web.1]: - Starting
2022-03-03T05:06:28.768363+00:00 app[web.1]: - Version: 4.31.7
2022-03-03T05:06:28.768699+00:00 app[web.1]: - Initializing WA
2022-03-03T05:06:28.771733+00:00 app[web.1]: - Launching Browser
2022-03-03T05:06:29.049156+00:00 app[web.1]: - Browser launched: 277ms
2022-03-03T05:06:29.081094+00:00 app[web.1]: - Setting Up Page
2022-03-03T05:06:29.094136+00:00 app[web.1]: - Loading session data
2022-03-03T05:06:29.098729+00:00 app[web.1]: - No session data file found for session : session
2022-03-03T05:06:29.102409+00:00 app[web.1]: - Existing session data detected. Injecting...
2022-03-03T05:06:29.108173+00:00 app[web.1]: - Existing session data injected
2022-03-03T05:06:29.109818+00:00 app[web.1]: - Pre page launch setup complete: 29ms
2022-03-03T05:06:29.113805+00:00 app[web.1]: - Navigating to WA
2022-03-03T05:06:30.770924+00:00 app[web.1]: - Page loaded in 1656ms: 200
2022-03-03T05:06:30.779061+00:00 app[web.1]: - Page loaded
2022-03-03T05:06:30.836499+00:00 app[web.1]: - Debug info: {
2022-03-03T05:06:30.836513+00:00 app[web.1]:   "WA_VERSION": "2.2206.9",
2022-03-03T05:06:30.836516+00:00 app[web.1]:   "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
2022-03-03T05:06:30.836516+00:00 app[web.1]:   "WA_AUTOMATE_VERSION": "4.31.7",
2022-03-03T05:06:30.836517+00:00 app[web.1]:   "BROWSER_VERSION": "HeadlessChrome/98.0.4758.102",
2022-03-03T05:06:30.836518+00:00 app[web.1]:   "OS": "Linux 4.4",
2022-03-03T05:06:30.836518+00:00 app[web.1]:   "START_TS": 1646283990792
2022-03-03T05:06:30.836518+00:00 app[web.1]: }
2022-03-03T05:06:31.988759+00:00 app[web.1]: - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2206.9%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.31.7%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/98.0.4758.102%22,%0A%20%20%22START_TS%22:%201646283990792,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%204.4%0A-%20Node:%2017.6.0%0A-%20npm:%208.5.1&labels=CLI,Legacy
2022-03-03T05:06:31.992700+00:00 app[web.1]: - Time to injection: 1213ms
2022-03-03T05:06:31.994432+00:00 app[web.1]: - Injecting api
2022-03-03T05:06:31.995222+00:00 app[web.1]: - Injecting scripts
2022-03-03T05:06:32.051069+00:00 app[web.1]: Error: Execution context was destroyed, most likely because of a navigation.
2022-03-03T05:06:32.051071+00:00 app[web.1]:     at rewriteError (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:265:23)
2022-03-03T05:06:32.051071+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-03T05:06:32.051073+00:00 app[web.1]:     at async ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:165:64)
2022-03-03T05:06:32.051073+00:00 app[web.1]:     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
2022-03-03T05:06:32.673575+00:00 app[web.1]: node:events:505
2022-03-03T05:06:32.673582+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2022-03-03T05:06:32.673583+00:00 app[web.1]:       ^
2022-03-03T05:06:32.673583+00:00 app[web.1]: 
2022-03-03T05:06:32.673584+00:00 app[web.1]: Error: spawn ps ENOENT
2022-03-03T05:06:32.673584+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
2022-03-03T05:06:32.673584+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:476:16)
2022-03-03T05:06:32.673585+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-03-03T05:06:32.673585+00:00 app[web.1]: Emitted 'error' event on ChildProcess instance at:
2022-03-03T05:06:32.673585+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-03-03T05:06:32.673586+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:476:16)
2022-03-03T05:06:32.673586+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-03-03T05:06:32.673586+00:00 app[web.1]:   errno: -2,
2022-03-03T05:06:32.673587+00:00 app[web.1]:   code: 'ENOENT',
2022-03-03T05:06:32.673587+00:00 app[web.1]:   syscall: 'spawn ps',
2022-03-03T05:06:32.673587+00:00 app[web.1]:   path: 'ps',
2022-03-03T05:06:32.673588+00:00 app[web.1]:   spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
2022-03-03T05:06:32.673588+00:00 app[web.1]: }
2022-03-03T05:06:32.673593+00:00 app[web.1]: 
2022-03-03T05:06:32.673594+00:00 app[web.1]: Node.js v17.6.0
2022-03-03T05:06:32.848098+00:00 heroku[web.1]: Process exited with status 1
2022-03-03T05:06:33.096758+00:00 heroku[web.1]: State changed from starting to crashed
2022-03-03T05:06:33.140588+00:00 heroku[web.1]: State changed from crashed to starting
2022-03-03T05:06:49.250917+00:00 heroku[web.1]: Starting process with command `/bin/sh -c PORT\=\19410\ WA_PORT\=\19410\ node\ ./node_modules/@open-wa/wa-automate/bin/server.js\ --use-chrome\ --force-port\=\19410\ --in-docker\ --qr-timeout\ 0`
2022-03-03T05:06:51.775583+00:00 app[web.1]: - session_STARTUP
2022-03-03T05:06:51.780167+00:00 app[web.1]: - DEBUG - PORT: 19410
2022-03-03T05:06:51.780747+00:00 app[web.1]: - DEBUG - flags: {"sessionId":"session","ev":false,"executablePath":"/usr/bin/google-chrome-stable","botPressUrl":"","debug":true,"keepUpdated":true,"port":19410,"popup":true,"keepAlive":false,"disableSpins":true,"socket":"","sessionData":"eyJXQUJyb3dzZXJJZCI6IlwidXBRblcxbUUwZGh0MDhWYVlaZ1NmUT09XCIiLCJXQVNlY3JldEJ1bmRsZSI6IntcImtleVwiOlwiMUpOZkdIMXp5SnFNYXc2cXNCUjZPNVRPNklyUUdodE5mQk5kdFRhaTNxST1cIixcImVuY0tleVwiOlwiK0gxMitrcjlzVGh0RnRFQ213NkNoQVBBS0h6L2ltWnk3NlBMWmM1b2t4Zz1cIixcIm1hY0tleVwiOlwiMUpOZkdIMXp5SnFNYXc2cXNCUjZPNVRPNklyUUdodE5mQk5kdFRhaTNxST1cIn0iLCJXQVRva2VuMSI6IlwiM3dHZER2Vmw4REVjQXVOcXd2L0xoNVkzSEZKTEtPUFU3dGp6cmpBbjhHTT1cIiIsIldBVG9rZW4yIjoiXCIxQGFGZFNHdi9jbmZJOTZHbWcvUlRnUFUyMENrNW04T0srYktKa1hVQmtLc3k2RlBReVVuNU05RitEQVA3Q3h1R2Y3K0ZEaFdLNW5yNG1udz09XCIifQ==","useChrome":true,"forcePort":19410,"inDocker":true,"qrTimeout":0,"noApi":false,"host":"localhost","verbose":false,"ef":["qr","STARTUP","MD_DETECT"],"allowSessionDataWh":false,"generateApiDocs":true,"sessionDataOnly":false,"skipSavePostmanCollection":false,"headful":false,"preAuthDocs":false,"stats":false,"noKillOnLogout":false,"cors":false,"emitUnread":false}
2022-03-03T05:06:51.781339+00:00 app[web.1]: - DEBUG - env vars: {"WA_EV":"false","WA_EXECUTABLE_PATH":"/usr/bin/google-chrome-stable","WA_BOT_PRESS_URL":"","WA_DEBUG":"true","WA_KEEP_UPDATED":"true","WA_PORT":"19410","WA_POPUP":"true","WA_KEEP_ALIVE":"false","WA_DISABLE_SPINS":"true","WA_WEBHOOK":"false","WA_SOCKET":"","WA_SESSION_DATA":"eyJXQUJyb3dzZXJJZCI6IlwidXBRblcxbUUwZGh0MDhWYVlaZ1NmUT09XCIiLCJXQVNlY3JldEJ1bmRsZSI6IntcImtleVwiOlwiMUpOZkdIMXp5SnFNYXc2cXNCUjZPNVRPNklyUUdodE5mQk5kdFRhaTNxST1cIixcImVuY0tleVwiOlwiK0gxMitrcjlzVGh0RnRFQ213NkNoQVBBS0h6L2ltWnk3NlBMWmM1b2t4Zz1cIixcIm1hY0tleVwiOlwiMUpOZkdIMXp5SnFNYXc2cXNCUjZPNVRPNklyUUdodE5mQk5kdFRhaTNxST1cIn0iLCJXQVRva2VuMSI6IlwiM3dHZER2Vmw4REVjQXVOcXd2L0xoNVkzSEZKTEtPUFU3dGp6cmpBbjhHTT1cIiIsIldBVG9rZW4yIjoiXCIxQGFGZFNHdi9jbmZJOTZHbWcvUlRnUFUyMENrNW04T0srYktKa1hVQmtLc3k2RlBReVVuNU05RitEQVA3Q3h1R2Y3K0ZEaFdLNW5yNG1udz09XCIifQ==","WA_USE_CHROME":"true"}
2022-03-03T05:06:51.781727+00:00 app[web.1]: - Launching EASY API
2022-03-03T05:06:51.806088+00:00 app[web.1]: - Selected port is free
2022-03-03T05:06:51.806800+00:00 app[web.1]: - --ev/-e expecting URL - invalid URL.
2022-03-03T05:06:51.807458+00:00 app[web.1]: - Generating Swagger Spec
2022-03-03T05:06:53.055764+00:00 app[web.1]: ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓┃                                                                              ┃┃   @open-wa/wa-automate                                                       ┃┃   💬 🤖 The most reliable NodeJS whatsapp library for chatbots with          ┃┃   advanced features.                                                         ┃┃   Version: 4.31.7                                                            ┃┃   Check out the latest changes:                                              ┃┃   https://github.com/open-wa/wa-automate-nodejs#latest-changes               ┃┃                                                                              ┃┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
2022-03-03T05:06:53.127761+00:00 app[web.1]: You can also authenticate the session at: NA
2022-03-03T05:06:53.128626+00:00 app[web.1]: - Starting
2022-03-03T05:06:53.129492+00:00 app[web.1]: - Version: 4.31.7
2022-03-03T05:06:53.129940+00:00 app[web.1]: - Initializing WA
2022-03-03T05:06:53.133129+00:00 app[web.1]: - Launching Browser
2022-03-03T05:06:53.299847+00:00 app[web.1]: - Browser launched: 166ms
2022-03-03T05:06:53.736074+00:00 app[web.1]: - Setting Up Page
2022-03-03T05:06:53.741737+00:00 app[web.1]: - Loading session data
2022-03-03T05:06:53.743078+00:00 app[web.1]: - No session data file found for session : session
2022-03-03T05:06:53.746226+00:00 app[web.1]: - Existing session data detected. Injecting...
2022-03-03T05:06:53.754234+00:00 app[web.1]: - Existing session data injected
2022-03-03T05:06:53.754805+00:00 app[web.1]: - Pre page launch setup complete: 19ms
2022-03-03T05:06:53.756923+00:00 app[web.1]: - Navigating to WA
2022-03-03T05:06:52.759331+00:00 app[web.1]: - Postman collection generated: open-wa-session.postman_collection.json
2022-03-03T05:06:52.957323+00:00 app[web.1]: - API collections (swagger + postman) generated successfully
2022-03-03T05:06:55.373583+00:00 app[web.1]: - Page loaded in 1614ms: 200
2022-03-03T05:06:55.373993+00:00 app[web.1]: - Page loaded
2022-03-03T05:06:55.741060+00:00 app[web.1]: - Debug info: {
2022-03-03T05:06:55.741069+00:00 app[web.1]:   "WA_VERSION": "2.2206.9",
2022-03-03T05:06:55.741072+00:00 app[web.1]:   "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
2022-03-03T05:06:55.741073+00:00 app[web.1]:   "WA_AUTOMATE_VERSION": "4.31.7",
2022-03-03T05:06:55.741073+00:00 app[web.1]:   "BROWSER_VERSION": "HeadlessChrome/98.0.4758.102",
2022-03-03T05:06:55.741074+00:00 app[web.1]:   "OS": "Linux 4.4",
2022-03-03T05:06:55.741074+00:00 app[web.1]:   "START_TS": 1646284015701
2022-03-03T05:06:55.741074+00:00 app[web.1]: }
2022-03-03T05:06:56.868002+00:00 app[web.1]: - Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&d_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2206.9%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.31.7%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/98.0.4758.102%22,%0A%20%20%22START_TS%22:%201646284015701,%0A%20%20%22LATEST_VERSION%22:%20true,%0A%20%20%22CLI%22:%20true%0A%7D&enviro=-%20OS:%20Linux%204.4%0A-%20Node:%2017.6.0%0A-%20npm:%208.5.1&labels=CLI,Legacy
2022-03-03T05:06:56.868479+00:00 app[web.1]: - Time to injection: 1493ms
2022-03-03T05:06:56.888858+00:00 app[web.1]: Error: Execution context was destroyed, most likely because of a navigation.
2022-03-03T05:06:56.888859+00:00 app[web.1]:     at rewriteError (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:265:23)
2022-03-03T05:06:56.888860+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-03T05:06:56.888862+00:00 app[web.1]:     at async ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:165:64)
2022-03-03T05:06:56.888863+00:00 app[web.1]:     at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
2022-03-03T05:06:56.955786+00:00 app[web.1]: node:events:505
2022-03-03T05:06:56.955788+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2022-03-03T05:06:56.955789+00:00 app[web.1]:       ^
2022-03-03T05:06:56.955789+00:00 app[web.1]: 
2022-03-03T05:06:56.955790+00:00 app[web.1]: Error: spawn ps ENOENT
2022-03-03T05:06:56.955790+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
2022-03-03T05:06:56.955791+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:476:16)
2022-03-03T05:06:56.955791+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-03-03T05:06:56.955791+00:00 app[web.1]: Emitted 'error' event on ChildProcess instance at:
2022-03-03T05:06:56.955792+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-03-03T05:06:56.955792+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:476:16)
2022-03-03T05:06:56.955792+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-03-03T05:06:56.955793+00:00 app[web.1]:   errno: -2,
2022-03-03T05:06:56.955793+00:00 app[web.1]:   code: 'ENOENT',
2022-03-03T05:06:56.955794+00:00 app[web.1]:   syscall: 'spawn ps',
2022-03-03T05:06:56.955794+00:00 app[web.1]:   path: 'ps',
2022-03-03T05:06:56.955794+00:00 app[web.1]:   spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
2022-03-03T05:06:56.955794+00:00 app[web.1]: }
2022-03-03T05:06:56.955800+00:00 app[web.1]: 
2022-03-03T05:06:56.955800+00:00 app[web.1]: Node.js v17.6.0
2022-03-03T05:06:57.120907+00:00 heroku[web.1]: Process exited with status 1
2022-03-03T05:06:57.169198+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by smashah** [comment]
is this still happening?

**Comment by scropion86** [comment]
yes , still on latest update as well

**Comment by smashah** [comment]
Very odd
I am not able to replicate this with my heroku account. Consider using DO instead

**Comment by scropion86** [comment]
i can confirm as on WA-automate version `4.35.10` the Heroku dploayment is working fine again.

but the note is due to WA is start forcing users to multiple devices and no way to revert the change, and since
MD session can't be portable as per [this ticket](https://github.com/open-wa/wa-automate-nodejs/issues/2338)
and sue to the nature of headless of heroku and the linitiation of the log system which prevent rendering the QR in a readable way i suggest to expose a QR URL so user can easily scan the QR code to start the session for example `app.herokuapp.com/qr`

i am closing the ticket as the crash on start is resolved
and has a suggested feature to expose the QR thrrough a URL

Thanks

**Comment by smashah** [comment]
@scropion86 I have added `--ezqr` to the heroku run command.

in the logs it will emit a URL which you can use to scan the qr code (e.g `https://qr.openwa.cloud/3f8b8`)

**Comment by smashah** [comment]
@scropion86 this is fixed now.

As soon as the session launches, the `/qr` endpoint is exposed e.g:

```
https://shielded-ocean-98229.herokuapp.com/qr
```
