### ISSUE TITLE
app[web.1]: - The session is invalid. Retrying

### ISSUE THREAD

**Issue by supreen** [open-wa/wa-automate-deploy-heroku#6]
getting this error, even after inserting the json.

**Comment by smashah** [comment]
@supreen this is not related to your session.json file itself. It is regarding the session itself as a whole. Please fill in the template to help fix this issue.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by supreen** [comment]
2021-03-02T18:49:30.177517+00:00 heroku[web.1]: Starting process with command `npm start`
2021-03-02T18:49:34.324968+00:00 app[web.1]: 
2021-03-02T18:49:34.325000+00:00 app[web.1]: > open-wa-deploy-heroku@1.0.0 start /app
2021-03-02T18:49:34.325016+00:00 app[web.1]: > npx @open-wa/wa-automate --disable-spins --port $PORT --popup --in-docker --qr-timeout 0 -k $API_KEY --keep-alive --keep-updated --executable-path="/app/.apt/usr/bin/google-chrome"
2021-03-02T18:49:34.325016+00:00 app[web.1]: 
2021-03-02T18:49:37.031342+00:00 app[web.1]: fresh run
2021-03-02T18:49:37.508756+00:00 app[web.1]: ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
2021-03-02T18:49:37.508767+00:00 app[web.1]: ┃                                                                                                   ┃
2021-03-02T18:49:37.508767+00:00 app[web.1]: ┃   @open-wa/wa-automate                                                                            ┃
2021-03-02T18:49:37.508768+00:00 app[web.1]: ┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
2021-03-02T18:49:37.508768+00:00 app[web.1]: ┃   Version: 3.1.10                                                                                 ┃
2021-03-02T18:49:37.508769+00:00 app[web.1]: ┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
2021-03-02T18:49:37.508769+00:00 app[web.1]: ┃                                                                                                   ┃
2021-03-02T18:49:37.508769+00:00 app[web.1]: ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
2021-03-02T18:49:37.960185+00:00 app[web.1]: You can also authenticate the session at: NA
2021-03-02T18:49:37.982582+00:00 app[web.1]: - Initializing WA
2021-03-02T18:49:38.392376+00:00 heroku[web.1]: State changed from starting to up
2021-03-02T18:49:39.714121+00:00 heroku[router]: at=info method=GET path="/" host=[app].herokuapp.com request_id=ddb20a66-354e-4037-b57e-f885f5d2a380 fwd="137.59.222.102" dyno=web.1 connect=1ms service=146ms status=304 bytes=237 protocol=https
2021-03-02T18:49:40.079814+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=polling&t=NVqHYNZ" host=[app].herokuapp.com request_id=ee692ca1-57d8-47ed-8c13-6d9ddba46e73 fwd="137.59.222.102" dyno=web.1 connect=1ms service=101ms status=200 bytes=232 protocol=https
2021-03-02T18:49:40.384786+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=4&transport=polling&t=NVqHYSV&sid=uIoSS3qjOmmWfA6EAAAA" host=[app].herokuapp.com request_id=0fd3ebdf-146d-4bda-889f-2846c57a2eca fwd="137.59.222.102" dyno=web.1 connect=1ms service=88ms status=200 bytes=121 protocol=https
2021-03-02T18:49:40.397005+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=polling&t=NVqHYSX&sid=uIoSS3qjOmmWfA6EAAAA" host=[app].herokuapp.com request_id=ba31d295-2e37-4b94-ae90-1bc3b7c093b7 fwd="137.59.222.102" dyno=web.1 connect=1ms service=100ms status=200 bytes=168 protocol=https
2021-03-02T18:49:41.455057+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=polling&t=NVqHYXS&sid=uIoSS3qjOmmWfA6EAAAA" host=[app].herokuapp.com request_id=6d3beb7b-7c18-41d4-ba9a-a05e229521a5 fwd="137.59.222.102" dyno=web.1 connect=4ms service=833ms status=200 bytes=136 protocol=https
2021-03-02T18:49:43.672758+00:00 app[web.1]: - Browser Launched
2021-03-02T18:49:43.827838+00:00 app[web.1]: ┌─────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
2021-03-02T18:49:43.827840+00:00 app[web.1]: │       (index)       │                                                                    Values                                                                    │
2021-03-02T18:49:43.827841+00:00 app[web.1]: ├─────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
2021-03-02T18:49:43.827841+00:00 app[web.1]: │     WA_VERSION      │                                                                  '2.2106.5'                                                                  │
2021-03-02T18:49:43.827842+00:00 app[web.1]: │       PAGE_UA       │ 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' │
2021-03-02T18:49:43.827842+00:00 app[web.1]: │ WA_AUTOMATE_VERSION │                                                                   '3.1.10'                                                                   │
2021-03-02T18:49:43.827842+00:00 app[web.1]: │   BROWSER_VERSION   │                                                        'HeadlessChrome/88.0.4324.182'                                                        │
2021-03-02T18:49:43.827843+00:00 app[web.1]: │         OS          │                                                                 'Linux 4.4'                                                                  │
2021-03-02T18:49:43.827844+00:00 app[web.1]: │      START_TS       │                                                                1614710983751                                                                 │
2021-03-02T18:49:43.827844+00:00 app[web.1]: └─────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
2021-03-02T18:49:43.830406+00:00 app[web.1]: - Authenticating
2021-03-02T18:50:43.859731+00:00 app[web.1]: - Authentication timed out. Please open the app on the phone. Shutting down
2021-03-02T18:50:44.070846+00:00 app[web.1]: Error App Offline Error: App Offline
2021-03-02T18:50:44.070848+00:00 app[web.1]:     at /app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:259:27
2021-03-02T18:50:44.070849+00:00 app[web.1]:     at step (/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:63:23)
2021-03-02T18:50:44.070850+00:00 app[web.1]:     at Object.next (/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:44:53)
2021-03-02T18:50:44.070850+00:00 app[web.1]:     at fulfilled (/app/node_modules/@open-wa/wa-automate/dist/controllers/initializer.js:35:58)

**Comment by smashah** [comment]
@supreen the error logs show that the mobile app is offline. Please make sure the mobile app is open and the phone is awake and connected to the internet when launching a session

**Comment by supreen** [comment]
Hi, my phone was online. it seems like the "deploy on heroku" button on the github is for some reason installing the ancient and deprecated version.  An other api just worked fine for me. Thankyou for responding

**Comment by smashah** [comment]
@supreen it should be fixed now I've updated the dependency. I will make sure it is kept up to date from now on using dependabot thanks
